version: "3"
services:
  node-app: # Image name = Foldername-node-app
    container_name: express-node-app-container
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db #named volume, not a bind mount or anonymous volumes .. (mongo-db just a name to avoid creating random name)
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express: # Mongo UI to manage the mongo DB
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
     - mongo   
  redis:
    image: redis
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
     - node-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # bind mount

volumes:
  mongo-db: