version: "3"
services:
  node-app: #Image name = Foldername-node-app
    container_name: express-node-app-container
    ports:
      - "4000:4000"
    env_file:
      - ./.env
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root